name: Add Feature to Upcoming on README

on:
  issues:
    types: [labeled, reopened]

jobs:
  update-readme:
    if: "(github.event.action == 'labeled' && github.event.label.name == 'enhancement') || (github.event.action == 'reopened' && contains(toJSON(github.event.issue.labels), '\"name\": \"enhancement\"'))"
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v2

      - name: Add to Readme
        run: echo "Haven't written the action to do this yet"

      - name: Comment on Issue
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: This has been added to the list of upcoming features.