name: Add Feature to Upcoming on README

on:
  issues:
    types: [labeled, reopened]

jobs:
  update-readme:
    if: github.event.label.name == 'enhancement'  # Might not work on reopened event
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Add to Readme
      - name: print label object
        uses: echo ${{ github.event.label }}
  comment-issue:
    needs: update-readme
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Comment on Issue
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: This has been added to the list of upcoming features.