name: Remove Feature from Upcoming on README

on:
  issues:
    types: [unlabeled, closed, deleted]

jobs:
  update-readme:
    # if: >
    #   (github.event.action == 'unlabeled' && github.event.label.name == 'enhancement') || 
      # (contains('closed, deleted', github.event.action) && contains(toJSON(github.event.issue.labels), '\"name\": \"enhancement\"'))
    runs-on: ubuntu-latest
    steps:
      - name: printing conditional
        run: "echo ${{ contains('closed, deleted', github.event.action) && contains(toJSON(github.event.issue.labels), '\"name\": \"enhancement\"') }}"

      - name: testing conditional
        if: >
          (contains('closed, deleted', github.event.action) && contains(toJSON(github.event.issue.labels), '\"name\": \"enhancement\"'))
        run: echo "how is this working?"

      - name: labels contain enhancements
        run: "echo ${{ contains(toJSON(github.event.issue.labels), '\"name\": \"enhancement\"') }}"
    # - name: Checkout
    #   uses: actions/checkout@v2

      - name: Add to Readme
        run: echo "Haven't written the action to do this yet"

      - name: Comment on Issue
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: This has been removed from the list of upcoming features.
