name: Remove Feature from Upcoming on README

on:
  issues:
    types: [unlabeled, closed, deleted]

jobs:
  update-readme:
    if: "(github.event.action == 'unlabeled' && github.event.label.name == 'enhancement' && github.event.issue.closed_at == '') || (contains('closed, deleted', github.event.action) && contains(toJSON(github.event.issue.labels), '\"name\": \"enhancement\"'))"
    runs-on: ubuntu-latest
    steps:
    # - name: Checkout
    #   uses: actions/checkout@v2

      - name: Add to Readme
        run: echo "Haven't written the action to do this yet"

      - name: Comment on Issue
        if: github.event.action != 'deleted'
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: This has been removed from the list of upcoming features.
